name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build

    - name: Run Tests
      run: dotnet test

    - name: Test and Collect Coverage
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Generate Coverage Report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.5.11
      with:
        reports: '**/TestResults/**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'MarkdownSummaryGithub;Html'

    - name: Publish Coverage to Job Summary
      run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

